/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'oxigdal.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.android-arm64.node')
          } else {
            nativeBinding = require('@oxigdal/node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'oxigdal.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.android-arm-eabi.node')
          } else {
            nativeBinding = require('@oxigdal/node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'oxigdal.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@oxigdal/node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'oxigdal.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@oxigdal/node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxigdal.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@oxigdal/node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'oxigdal.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxigdal.darwin-universal.node')
      } else {
        nativeBinding = require('@oxigdal/node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'oxigdal.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.darwin-x64.node')
          } else {
            nativeBinding = require('@oxigdal/node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'oxigdal.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.darwin-arm64.node')
          } else {
            nativeBinding = require('@oxigdal/node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'oxigdal.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./oxigdal.freebsd-x64.node')
      } else {
        nativeBinding = require('@oxigdal/node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-x64-musl.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'oxigdal.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./oxigdal.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@oxigdal/node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'oxigdal.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./oxigdal.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@oxigdal/node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { ResamplingMethod, resample, calculate, buffer, area, simplify, hillshade, slope, aspect, zonalStats, openRasterAsync, saveRasterAsync, readGeojsonAsync, writeGeojsonAsync, resampleAsync, hillshadeAsync, slopeAsync, aspectAsync, zonalStatsAsync, bufferAsync, areaAsync, simplifyAsync, batchProcessRasters, setProgressCallback, CancellationToken, processRasterParallel, RasterStream, BufferWrapper, createBuffer, bufferFromBytes, createError, getErrorCodes, Dataset, openRaster, createRaster, Feature, GeometryWrapper, FeatureCollection, readGeojson, writeGeojson, version, name, getInfo, getDataTypes, getResamplingMethods } = nativeBinding

module.exports.ResamplingMethod = ResamplingMethod
module.exports.resample = resample
module.exports.calculate = calculate
module.exports.buffer = buffer
module.exports.area = area
module.exports.simplify = simplify
module.exports.hillshade = hillshade
module.exports.slope = slope
module.exports.aspect = aspect
module.exports.zonalStats = zonalStats
module.exports.openRasterAsync = openRasterAsync
module.exports.saveRasterAsync = saveRasterAsync
module.exports.readGeojsonAsync = readGeojsonAsync
module.exports.writeGeojsonAsync = writeGeojsonAsync
module.exports.resampleAsync = resampleAsync
module.exports.hillshadeAsync = hillshadeAsync
module.exports.slopeAsync = slopeAsync
module.exports.aspectAsync = aspectAsync
module.exports.zonalStatsAsync = zonalStatsAsync
module.exports.bufferAsync = bufferAsync
module.exports.areaAsync = areaAsync
module.exports.simplifyAsync = simplifyAsync
module.exports.batchProcessRasters = batchProcessRasters
module.exports.setProgressCallback = setProgressCallback
module.exports.CancellationToken = CancellationToken
module.exports.processRasterParallel = processRasterParallel
module.exports.RasterStream = RasterStream
module.exports.BufferWrapper = BufferWrapper
module.exports.createBuffer = createBuffer
module.exports.bufferFromBytes = bufferFromBytes
module.exports.createError = createError
module.exports.getErrorCodes = getErrorCodes
module.exports.Dataset = Dataset
module.exports.openRaster = openRaster
module.exports.createRaster = createRaster
module.exports.Feature = Feature
module.exports.GeometryWrapper = GeometryWrapper
module.exports.FeatureCollection = FeatureCollection
module.exports.readGeojson = readGeojson
module.exports.writeGeojson = writeGeojson
module.exports.version = version
module.exports.name = name
module.exports.getInfo = getInfo
module.exports.getDataTypes = getDataTypes
module.exports.getResamplingMethods = getResamplingMethods
